### ISSUE TITLE
Adding new values to maps

### ISSUE THREAD

**Issue by pkgodara** [Cleidiano/warpath#118]
Is it possible to add new values? update/3 does nothing if element doesn't already exist.

Example:

> Warpath.update(%{"a" => 1}, "$.b", fn (_) -> 3 end)

{:ok, %{"a" => 1, "b" => 3}}

**Comment by cleidiano** [comment]
Hi @pkgodara, this indeed is a powerful feature, but since the expression should be expanded before we do a final operation it come with some corner cases, I will evaluate and and think carefully how to design it.

I will take a time to think about it and post back to enumerate all corner cases and discuss how to address it.
In this particular usecase you could address it selecting the left most parent node and doing the operation at the update function. (after merge #119)
`Warpath.update(%{"a" => 1}, "$", fn node -> Map.put_new(node, "b", 3) end)`.

Maybe we can add a small change to update/3 to support the function update like `fn path, node -> end`, this will help to gather info about which path the update/3 is current operate on, let me know if this could help in your useases.

**Comment by cleidiano** [comment]
Hi, @pkgodara
I have been thinking and trying to figure out how it could be implemented. It's very hard to properly implement this feature because of the nature of jsonpath that some selectors need to be expanded, like `wildcard`,  `scan` and `filter`.

To properly put an item into a map, we need the absolute path of  item and the path expansion is evaluated against the existent data. Once any middle data is missing, the path couldn't be expanded, once the path couldn't be expanded, the absolute path to put the data would be undetermined. 
This is the behaviour you experienced in your example, since the path doesn't exist, you update function wasn't called.

I think we could implement this feature as long as the behaviour to only operate on existent data are kept, similar as `update/3` does, if jsonpath expression evaluates nothing, the input data structure should be returned.

I propose to add two new functions:
- `Warpath.insert/3` to insert data into a list, ex:  `Warpath.insert(store, ~q"$.store.book",  %{"author" => ....}`)
- `Warpath.put/4` to put data into a map, ex:  `Warpath.put(store, ~q"$.store.book[0]", :language, "pt-BR" `)

**Comment by cleidiano** [comment]
> Hi, @pkgodara
> I have been thinking and trying to figure out how it could be implemented. It's very hard to properly implement this feature because of the nature of jsonpath that some selectors need to be expanded, like `wildcard`, `scan` and `filter`.
> 
> To properly put an item into a map, we need the absolute path of item and the path expansion is evaluated against the existent data. Once any middle data is missing, the path couldn't be expanded, once the path couldn't be expanded, the absolute path to put the data would be undetermined.
> This is the behaviour you experienced in your example, since the path doesn't exist, you update function wasn't called.
> 
> I think we could implement this feature as long as the behaviour to only operate on existent data are kept, similar as `update/3` does, if jsonpath expression evaluates nothing, the input data structure should be returned.
> 
> I propose to add two new functions:
> 
>     * `Warpath.insert/3` to insert data into a list, ex:  `Warpath.insert(store, ~q"$.store.book",  %{"author" => ....}`)
> 
>     * `Warpath.put/4` to put data into a map, ex:  `Warpath.put(store, ~q"$.store.book[0]", :language, "pt-BR" `)

The proposed function won't improve the api since it's behavior should be keep equals as `update/3`, instead `Warpath.update/3` should be used, with addition of #126 now it's possible to pattern match on path.
