### ISSUE TITLE
Question: singular result vs list of results

### ISSUE THREAD

**Issue by mmmries** [Cleidiano/warpath#91]
👋  Hi and thank you for an awesome library!

I'm considering using your library for a production project and I would also love to contribute a little as part of [Hacktoberfest](https://hacktoberfest.digitalocean.com/) if there's something I can help with.

One thing I noticed as I was working with warpath is that in some cases a query will result in a single scalar value where I think other implementations would return a list with a single result. I'm wondering if there is a specific reason for this, or if I can help contribute a fix for this use-case. Here's an example:

```elixir
json_data = %{
          "CustomField" => [
            %{"Id" => 123, "Name" => "OPID", "Value" => "000XF1D"},
            %{"Id" => 456, "Name" => "Tags", "Value" => ["T1", "T2", "T3"]},
            %{"Id" => 789, "Name" => "Recurring", "Value" => false}
          ]
        }

Warpath.query!(json_data, "$.CustomField[0].Name") # => "OPID", I would expect ["OPID"] in this case
```

**Comment by cleidiano** [comment]
Hi @mmmries, thank you for the interest int the library!
Produce scalar value was a choice by design when the only possible value is a scalar result.

Currently I freezing the development a little bit, because there are a initiative to produce [JsonPath Specification](https://github.com/jsonpath-standard/internet-draft) and I'am keep track on that!

It's amazing to know that you are planning to use the library in production, the only warn is that the library is not stable yet, so if you find any bugs, feel free to report here.

**Comment by mmmries** [comment]
@Cleidiano sounds good. I'll keep an eye on that specification effort as well. Hopefully we can get a cross-implementation standard. I'll close this issue since the behavior I reported is intended.
